### PR TITLE
flexp-browser trims text files

### LINKED ISSUE #3: [flexp-browser] Trim text files to reasonable size by default

### PR DESCRIPTION
**Pull request by ofilip**
close #3

### CODE REVIEW

**Comment by alaneckhardt** [comment]
LGTM, didn't test it. I'll merge it tomorrow.

**Comment by tomasprinda** [comment]
Thanks, this feature was missing. 

The same feature is in `CsvToHtml.max_rows`, it would be nice if the variable names would have the same names.
https://github.com/seznam/flexp/blob/25e1cd881c29bd9bcef27a490992b2a3266b1599/flexp/browser/html/generic.py#L254

**Comment by alaneckhardt** [comment]
+1 to Tomas for the first intercontinental comment!

**Comment by ofilip** [comment]
`trim_at` renamed to `max_rows`

**Pull request merged**
