### PR TITLE
added experiment-dir param to flexp-browser

### LINKED ISSUE #14: Experiments dir as a command line parameter in flexp-browser
```bash
flexp-browser --experiments_dir ./experiments
```
 instead of 

```bash 
cd experiments
flexp-browser  &
cd ..
```

### PR DESCRIPTION
**Pull request by tivvit**
fixes #14 

did a little cleanup in the file too

### CODE REVIEW

**Comment by tomasprinda** [comment]
There is some problem with TxtToHtml module. Check screenshot.

All experiments are red - it is done by checking if some file exists in the folder. If not, it is red so the file is not found even if it is there.

screenshot from 2018-10-23 09-08-40

I ran it by 
```bash
flexp-browser --experiments_dir experiments/
```

To get the exception message you can use
```bash
git rebase 20-show-exception-message-in-to_html_2
```

**Comment by tivvit** [comment]
i will take a look at it

**Comment by tomasprinda** [comment]
Then we can also edit the [documentation](https://github.com/seznam/flexp/blob/master/flexp/browser/README.md).

**Comment by tomasprinda** [comment]
MR #31 is update of this MR.

**Pull request closed without merging**
