### PR TITLE
travis CI tests

### PR DESCRIPTION
**Pull request by tivvit**

### CODE REVIEW

**Comment by tivvit** [comment]
closes #15

**Comment by tivvit** [comment]
Tests are not working in python2.7 should it @alaneckhardt?
```
Traceback:
tests/test_cache_attrs.py:7: in <module>
    from flexp.flow import cache
flexp/flow/__init__.py:1: in <module>
    from flexp.flow.flow import *
flexp/flow/flow.py:10: in <module>
    from flexp.utils import get_logger
flexp/utils.py:1: in <module>
    import importlib.machinery
E   ImportError: No module named machinery
```

**Comment by tivvit** [comment]
It may be merged now @alaneckhardt @ofilip 

Depends on if python2.7 should work

**Comment by ofilip** [comment]
How did you enable the CI? It is only about adding .travis.iml?

**Comment by tivvit** [comment]
No Travis has to be enabled for the project. We solved it in a issue #14 I
wasn't able to do it because of permissions (I think the problem was that I
was not present in the Seznam group). Ondras added me to the group and
added tragic for the project too.

**Pull request merged**
